### ISSUE TITLE
ONE Line protocol support.

### ISSUE THREAD

**Issue by Vallerik** [SnijderC/dyplayer#20]
Hello! Great library, I am delighted but also frustrated at the same time. Since there is no support for the ONE Line protocol. Can you add it? I really wanted to deal with him and control the player using only one wire.

**Comment by SnijderC** [comment]
Hi Vallerik, 

Unfortunately that protocol is entirely different from the UART protocol, not only in its hardware interface, but also every command and parameter is different. Instead I suggest you to just connect a UART TX pin from your microcontroller to the RX pin on the sound module, you will not get any feedback, so don't use functions that return a value from the module. But you have the same level of control with as many wires as the ONE Line protocol. 

Does that help?

**Comment by Vallerik** [comment]
Hello!  Thanks for the answer!  I understood you.  But I want to deal with the ONE Line protocol, for some of my Arduino projects this connection is needed.  Could you help me?  Will make at least a simple example for sending one command over this protocol?


Вторник, 18 августа 2020, 13:31 +03:00 от Chris <notifications@github.com>:
>Hi Vallerik,
>Unfortunately that protocol is entirely different from the UART protocol, not only in its hardware interface, but also every command and parameter is different. Instead I suggest you to just connect a UART TX pin from your microcontroller to the RX pin on the sound module, you will not get any feedback, so don't use functions that return a value from the module. But you have the same level of control with as many wires as the ONE Line protocol.
>Does that help?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

С уважением,
Валера Залит
valera.zalit@inbox.ru

**Comment by SnijderC** [comment]
I'm not adding support to this library, also not through pull request because the protocols are too different.

There is a manual floating around the internet with instructions on each protocol, hardware connections etc. If you don't have that manual, I can maybe help you find that, does that help you?

**Comment by Vallerik** [comment]
Good. I realized that you will not add this protocol.
I just wanted to ask for a simple example of a one line control program. If it's not difficult for you, please send a manual or a simple example program.

  
>Среда, 19 августа 2020, 13:25 +03:00 от Chris <notifications@github.com>:
> 
> 
>I'm not adding support to this library, also not through pull request because the protocols are too different.
>There is a manual floating around the internet with instructions on each protocol, hardware connections etc. If you don't have that manual, I can maybe help you find that, does that help you?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Валера Залит
valera.zalit@inbox.ru

**Comment by arduino12** [comment]
**Hi,**

@SnijderC  I just made a simple library to control the DY_SV17F module that I got [**dy_sv17f_wire**](https://github.com/arduino12/dy_sv17f_wire),

It will be helpfull if you can drop a link to my repo in this repo README,
Anyway I have added a link to your repo in mine :)
