### ISSUE TITLE
ibrary  dyplayer-master version 4.0.0  ld returned 1 exit status

### ISSUE THREAD

**Issue by dnguyen76** [SnijderC/dyplayer#22]
I have made an Arduino IDE program for ESP32 by copy of your  PlaySounds.cpp program in Exemples/ESP32
But a get an ld error : undefined reference to `DY::Player::Player(uart_port_t, unsigned char, unsigned char)'

I am lost and don't know how to fix it
Thanks for your help
______________________________________________________________________________________________

include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <esp_log.h>
#include <driver/uart.h>
#include "DYPlayerESP32.h"

#define TAG "dyplayer"

DY::Player  player(UART_NUM_2,(uint8_t) 18, (uint8_t)19);

void setup() {
  // put your setup code here, to run once:
  // Initialise the player on uart2, pins TX: 18, RX: 19.
// player(UART_NUM_2, (uint8_t)18,(uint8_t) 19);
  
}

void loop() {
  // put your main code here, to run repeatedly:

  vTaskDelay(1000 / portTICK_PERIOD_MS);
  player.setVolume(15); // 50% Volume

  ESP_LOGI(TAG, "Sound count: %u", (uint8_t) player.getSoundCount());
  ESP_LOGI(TAG, "Player device %u", (uint8_t) player.getDeviceOnline());
  while (true) {
    // Change to next sound after 5 seconds (non-blocking call so will cut off
    // currently playing sound if any).
    for (uint8_t i = 1; i < player.getSoundCount(); i++) {
      player.playSpecified(i);
      ESP_LOGI(TAG, "Playing song %d", player.getPlayingSound());
      vTaskDelay(5000 / portTICK_PERIOD_MS);
    }
    vTaskDelay(10000 / portTICK_PERIOD_MS);
  }
}

_______________________________________________________________________________________________________
Linking everything together...

**C:\Users\Dan\AppData\Local\Temp\arduino_build_877896\sketch\sketch_oct02a.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_player+0x4): undefined reference to `DY::Player::Player(uart_port_t, unsigned char, unsigned char)'

C:\Users\Dan\AppData\Local\Temp\arduino_build_877896\sketch\sketch_oct02a.ino.cpp.o: In function `_GLOBAL__sub_I_player':

C:\Users\Dan\Documents\Arduino\sketch_oct02a/sketch_oct02a.ino:9: undefined reference to `DY::Player::Player(uart_port_t, unsigned char, unsigned char)'

collect2.exe: error: ld returned 1 exit status**

Use of library  dyplayer-master version 4.0.0 dans le dossier: C:\Users\Dan\Documents\Arduino\libraries\dyplayer-master 

exit status 1

**Comment by SnijderC** [comment]
You're using Arduino, which means your platform is Arduino, not ESP32. It may be confusing but ESP32 has it's own framework called [esp-idf](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/) that's what this example is for. 

If you use the Arduino Framework, just use the Arduino examples.
