### ISSUE TITLE
Commands working fine however can't get valid response

### ISSUE THREAD

**Issue by Orel-A** [SnijderC/dyplayer#24]
I'm using ESP8266 connected to DY-SV17F. I'm able to send commands to the module but attempting to use the functions checkPlayState / getPlayingSound I'm unable to get a valid response. Seems like I get garbled data. Not sure how to further debug this as I don't have any ideas as to why sending data is working fine but getting back data not.

**Comment by SnijderC** [comment]
Can you tell me how you connected the module? Did you use a resistor on the RX line?

**Comment by Orel-A** [comment]
I followed the instructions here in the segment "Wiring the module". I didn't use a resistor on the RX line.

**Comment by Orel-A** [comment]
Well, right now it's not too inportant as I've managed to solve my problem by using the Busy pin on the module.
