### ISSUE TITLE
Fix play_mode_t in readme.md

### ISSUE THREAD

**Issue by woutput** [SnijderC/dyplayer#31]
[DYPlayer.h](https://github.com/SnijderC/dyplayer/blob/3c095de64221db749698d712b03336c81e49c5d3/src/DYPlayer.h) says in line 62:

```
  typedef enum PlayMode: uint8_t {
    Repeat,       // Play all music in sequence, and repeat.
    RepeatOne,   // Repeat current sound.
    OneOff,      // Play sound file and stop.
    Random,       // Play random sound file.
    RepeatDir,   // Repeat current directory.
    RandomDir,   // Play random sound file in current folder.
    SequenceDir, // Play all sound files in current folder in sequence, and stop.
    Sequence      // Play all sound files on device in sequence, and stop.
  } play_mode_t;
```
and [DYPlayer.h](https://github.com/SnijderC/dyplayer/blob/3c095de64221db749698d712b03336c81e49c5d3/src/DYPlayer.h) on line 284:

`      void setCycleMode(play_mode_t mode);
`

while [readme.md](https://github.com/SnijderC/dyplayer/blob/master/README.MD) says:

`void `DY::DYPlayer::setCycleMode(..)

Sets the cycle mode. See `DY::play_state_t` for modes and meaning.
  | Type | Name | Description
-- | -- | -- | --
param | play_mode_t | mode | mode The cycle mode to set

So I think that DY::play_state_t should be replaced by DY::play_mode_t in readme.md. In addition, play_mode_t should be added to readme.md.
It would make the text "Set how many cycles to play when in cycle modes 0, 1 or 4 (repeat modes)." at setCycleTimes understandable.

P.S. Thanks for sharing this library 😄

**Comment by SnijderC** [comment]
Thanks for providing this feedback, I've added it and swapped out the names as you suggested.
