### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by katrinaangelie** [SnijderC/dyplayer#33]
:)

**Comment by katrinaangelie** [comment]
I used 001 and 010 configuration pin.

**Comment by harryberlin** [comment]
i think the device is an other one

**Comment by katrinaangelie** [comment]
From the picture above the  voice module is sv-8f but i am using sv5w. But the connection is the same.

**Comment by harryberlin** [comment]
is the dyplayer protocol the same?
try SoftwareSerial

**Comment by katrinaangelie** [comment]
I tried it alao

**Comment by katrinaangelie** [comment]
Anyone can help me for the connection and codes.
I just want to play the sv5w what ever i pick to the sd card.
