### ISSUE TITLE
ESP8266 with DY-5V5W mini MP3 player - won't compile

### ISSUE THREAD

**Issue by hicksan** [SnijderC/dyplayer#39]
Thank you very much for this fantastic library.

I have downloaded and installed it and am trying to get started with an ESP8266 Wemos D1 (Uno format) board.

I am trying your demo files, with the dyplayeresp32.h library but I get compile errors:
"'DY' does not name a type" and "'player' was not declared in this scope".

The only modification to the files is to point to the dyplayeresp32.h library.

I added the line #define ESP_PLATFORM 1 above the #include for your library. Now it says it cannot locate "driver/uart.h"

Please may you advise where I am going wrong. Probably something basic fundamental.

**Comment by SnijderC** [comment]
ESP8266 is not compatible with ESP32, you can still use it as an Arduino board though.
