### ISSUE TITLE
Small delay between track?

### ISSUE THREAD

**Issue by sbarabe** [SnijderC/dyplayer#46]
Hi !
I'm working on a cosplay project using the DY-SV8F and using this librairy. It's working pretty well, thanks a lot for this great work.

My only issue is that there is a small delay between sounds. I just wonder if it's a board issue or if there is a way to call sounds wi no playing delay? Or maybe it's a controller issue? I'm using nano board with softaerial

Regards!

**Comment by SnijderC** [comment]
I think this is inherent to the way the board works. One thing you can do is make sure there is absolutely no quiet part at the start of the file. Second, I didn't try this yet, is to see what happens with lower vs higher bitrate files etc. I can imagine it takes an underpowered microcontroller a bit of time to read the file from memory. 

Would love to see what you created!
