### ISSUE TITLE
Entering the equalizer settings command

### ISSUE THREAD

**Issue by pav72el** [SnijderC/dyplayer#56]
Hello. I want to thank you for your work. I tried your code and everything works fine for me. I connect DY-17SF via uart. The only thing I can't figure out is how to change the equalizer settings. I don't understand the Arduino code very well, I'm still learning it. I have a question: is it possible to set equalizer settings in a sketch using a command similar to the volume command? If yes, please give an example. Thank you.

**Comment by larrybud2004** [comment]
Use the setEq method:

`  void DYPlayer::setEq(eq_t eq)`
